name: Validate
concurrency:
  group: 'main'
  cancel-in-progress: true

on: push
jobs:
  validate:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
      SKU_TELEMETRY: false
    steps:
      - name: Check out repo
        uses: actions/checkout@master
        with:
          lfs: true

      - name: Set up Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: format
        run: yarn format

      - name: test
        run: yarn test
